### ISSUE TITLE
Convert to ReStructuredText

### ISSUE THREAD

**Issue by t0xicCode** [mgifford/drupal-security#8]
While markdown is fine for light uses and conversion to HTML, ReStructuredText, or RST, is better suited for conversion to formats such as pdf, and gives us more flexibility in the supported construct.

If I get some support, I'll convert the document to rst using pandoc.

**Comment by t0xicCode** [comment]
@mgifford

**Comment by mgifford** [comment]
Just saw this..  

Suzanne wrote a good piece on it here http://evolvingweb.ca/story/writing-documentation-restructured-text-and-sphinx

Several tools to export http://docutils.sourceforge.net/docs/user/links.html#export

even to epub - https://github.com/mattharrison/rst2epub2
https://bitbucket.org/wierob/rst2epub
http://sphinx-doc.org/
http://johnmacfarlane.net/pandoc/
http://www.docverter.com/learn

I like ePub as it is more accessible than PDF.  I'd rather have more folks making ePub if we can.

@nerdcorenet  - any thoughts on this?

Mike
